import Head from "next/head";
import Link from "next/link";
import Calendar from "../components/Calendar";
import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className=" flex h-30 w-full color bg-[rgb(87,65,87)] text-[30px] pl-5">
          <img src="lashify.png" alt="logo" className="w-20 h-20 " />
        </div>
        <Calendar />
      </main>
    </>
  );
}
