import Head from "next/head";
import Link from "next/link";
import Calendar from "../components/Calendar";
import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="h-[8vh] w-full color bg-[#df8080] text-[30px] text-center">Lashify</div>
        <Calendar />
      </main>
    </>
  );
}
